apiVersion: v1
kind: Namespace
metadata:
  name: uptime-tool

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: uptime-tool
  namespace: uptime-tool
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - uptime-tool.asrr-tech.com
    secretName: uptime-tool-tls
  rules:
  - host: uptime-tool.asrr-tech.com
    http:
      paths:
        - path: /
          backend:
            serviceName: uptime-tool
            servicePort: 5678

---

apiVersion: v1
kind: Service
metadata:
  name: uptime-tool
  namespace: uptime-tool
spec:
  selector:
    app: uptime-tool
  ports:
  - port: 5678

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-tool
  namespace: uptime-tool
  labels:
    app: uptime-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-tool
  template:
    metadata:
      namespace: uptime-tool
      labels:
        app: uptime-tool
    spec:
      containers:
      - name: uptime-tool
        image: hashicorp/http-echo
        args:
          - "-text=apple"